#ifndef GPIO_DEFINITIONS_H
#define GPIO_DEFINITIONS_H

#define SENSOR_HOUR GPIO_NUM_1
#define SENSOR_MINUTE GPIO_NUM_2

#define SDA_PIN GPIO_NUM_8
#define SCL_PIN GPIO_NUM_9

#define MOTOR_HOUR_DIR GPIO_NUM_4
#define MOTOR_HOUR_STEP GPIO_NUM_3
#define MOTOR_MIN_DIR GPIO_NUM_0
#define MOTOR_MIN_STEP GPIO_NUM_5
#define MOTOR_HOUR_TX GPIO_NUM_20
#define MOTOR_HOUR_RX GPIO_NUM_21
#define MOTOR_MIN_TX GPIO_NUM_20
#define MOTOR_MIN_RX GPIO_NUM_21

#endif // GPIO_DEFINITIONS_H
